Update react.yml

diff --git a/.github/workflows/react.yml b/.github/workflows/react.yml
--- a/.github/workflows/react.yml
+++ b/.github/workflows/react.yml
@@ -16,8 +16,22 @@ jobs:
         with:
           node-version: 14
 
-      - name: Checking dir
-        run: ls
+      - name: Changing the Working Dir
+        run: cd chitfront
+      
+      - name: Check working directory
+        run: |
+          if [ "$(basename "$PWD")" != "chitfront" ]; then
+            echo "Error: Not in the 'chitfront' directory"
+            exit 1
+          fi
+      
+      - name: Check package.json
+        run: |
+          if [ ! -f "package.json" ]; then
+            echo "Error: 'package.json' file not found"
+            exit 1
+          fi
 
       - name: Install dependencies
         run: npm ci
